### ISSUE TITLE
SSL.com ACME support for free 90 day SSL/TLS certs

### ISSUE THREAD

**Issue by codelux** [webprofusion/acme-clients#103]
You should add SSL.com as a CA that supports ACME for free 90 day certificates to expand your list: 

https://www.ssl.com/how-to/order-free-90-day-ssl-tls-certificates-with-acme/

**Comment by webprofusion-chrisc** [comment]
Thanks, they're already on the list but if there's something you think needs changed feel free to edit and submit as a PR: https://github.com/webprofusion/acme-clients/blob/main/src/_data/ca.json
