### ISSUE TITLE
Traefik

### ISSUE THREAD

**Issue by lonix1** [webprofusion/acme-clients#111]
Is traefik not an example of "Products with Integrated ACME support"?

**Comment by webprofusion-chrisc** [comment]
Sorry I don't use Traefik so you'd have to tell me. 

Does it use some other tool for its acme or does it provide that itself? Feel free to submit a PR for the json file change.

**Comment by webprofusion-chrisc** [comment]
Cool, we definitely mention Lego already, but we can also mention Traefik.
