### ISSUE TITLE
zerossl ca: not every feature available for free

### ISSUE THREAD

**Issue by AvverbioPronome** [webprofusion/acme-clients#2]
https://github.com/webprofusion/acme-clients/blob/1d12e15ffa48a3cd1cd4c9a23a1944f6091b0d44/src/_data/ca.json#L78-L82

this also applies to the point about their sustenance. their free plan just has 3 certificates without even SAN. https://zerossl.com/pricing/

OH, OK, I'm an idiot: they're only free if you get them through ACME: https://zerossl.com/features/acme/ (and that includes wildcards as well)

a probable pro of theirs could be their not being US based, a kind of legal redundancy, but being that their intermediate is signed by sectigo and I haven't found their own root... I'm not sure.

**Comment by webprofusion-chrisc** [comment]
Thanks, yeah the current pros/cons are fairly subjective so happy to adjust them.
