### ISSUE TITLE
Let's Encrypt Rate limits

### ISSUE THREAD

**Issue by Giga-Pudding** [webprofusion/acme-clients#49]
Hi,

The webpage [ACME Certificate Authorities](https://acmeclients.com/certificate-authorities/) states for Let's Encrypt: _Rate limits apply (hard - not user changeable)_

But the Let's Encrypt Documentation states, that one can request higher limits - at least hosters and companys can apply for higher limits:

https://letsencrypt.org/docs/rate-limits/

_If you are a large hosting provider or organization working on a Let’s Encrypt integration, we have a [rate limiting form](https://goo.gl/forms/plqRgFVnZbdGhE9n1) that can be used to request a higher rate limit. It takes a few weeks to process requests, so this form is not suitable if you just need to reset a rate limit faster than it resets on its own._

Okay, you could now argue that this offer is not available for EndUSERs, but a single user will hardly reach the normal limits. If you do, you should consider to found a company :)

I would kindly ask to update the webpage, since it is not a hard limit.

**Comment by webprofusion-chrisc** [comment]
Sorry, missed this issue - fixed now https://github.com/webprofusion/acme-clients/commit/d24304cd90e8a0c5dd577c78d4ae4475deaabf6b
